# Generated by Django 4.0.3 on 2022-04-03 17:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_rename_title_todo_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='added_date',
            field=models.DateField(default=datetime.date(2022, 4, 3)),
        ),
        migrations.AddField(
            model_name='todo',
            name='due_date',
            field=models.DateField(default=datetime.date(2022, 4, 3)),
        ),
    ]
