# Generated by Django 4.0.3 on 2022-04-03 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_todo_added_date_todo_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='status',
            field=models.CharField(choices=[('completed', 'Completed'), ('active', 'Active'), ('overdue', 'Overdue')], default='active', max_length=9),
        ),
    ]
